# Generated by Django 5.0 on 2025-01-10 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EduaddaCourse',
            fields=[
                ('COURSE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('DESCRIPTION', models.TextField(blank=True, default='', null=True)),
                ('THUMBNAIL', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('VIDEO', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('PRICE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Eduadda_course',
            },
        ),
        migrations.CreateModel(
            name='EduaddaNotes',
            fields=[
                ('NOTES_ID', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('DESCRIPTION', models.TextField(blank=True, default='', null=True)),
                ('THUMBNAIL', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('PDF', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('PRICE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Eduadda_notes',
            },
        ),
        migrations.CreateModel(
            name='EduaddaUser',
            fields=[
                ('USER_ID', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('EMAIL', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('IS_ACTIVE', models.IntegerField(blank=True, default=1, null=True)),
                ('PASSWORD', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('PR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Eduadda_user',
            },
        ),
        migrations.CreateModel(
            name='EduaddaNotesPurchase',
            fields=[
                ('PURCHASE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PURCHASE_DATE', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
                ('NOTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduaddaApp.eduaddanotes')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduaddaApp.eduaddauser')),
            ],
            options={
                'db_table': 'Eduadda_notes_purchase',
            },
        ),
        migrations.CreateModel(
            name='EduaddaCoursePurchase',
            fields=[
                ('PURCHASE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PURCHASE_DATE', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduaddaApp.eduaddacourse')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduaddaApp.eduaddauser')),
            ],
            options={
                'db_table': 'Eduadda_course_purchase',
            },
        ),
    ]
