# Generated by Django 5.0 on 2025-01-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduaddaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CbtBanner',
            fields=[
                ('PR_BANNER_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PR_TITLE', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('PR_IMAGE', models.CharField(blank=True, default='/media/default-img.png', max_length=255, null=True)),
                ('PR_STATUS', models.IntegerField(blank=True, default=0, null=True)),
                ('PR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cbt_banner',
            },
        ),
        migrations.AlterField(
            model_name='eduaddacourse',
            name='THUMBNAIL',
            field=models.CharField(blank=True, default='/media/default-img.png', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eduaddanotes',
            name='THUMBNAIL',
            field=models.CharField(blank=True, default='/media/default-img.png', max_length=255, null=True),
        ),
    ]
