# Generated by Django 5.0 on 2025-01-10 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduaddaApp', '0002_cbtbanner_alter_eduaddacourse_thumbnail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CbtBanner',
            new_name='EduaddaBanner',
        ),
        migrations.AlterModelTable(
            name='eduaddabanner',
            table='Eduadda_banner',
        ),
    ]
