# Generated by Django 5.0 on 2025-01-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduaddaApp', '0003_rename_cbtbanner_eduaddabanner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduaddaFileData',
            fields=[
                ('PR_FILE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PR_FILE', models.FileField(blank=True, null=True, upload_to='media/file-data/')),
                ('PR_META_TAG', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('PR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Eduadda_file_data',
            },
        ),
    ]
