# Generated by Django 5.0 on 2025-01-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduaddaApp', '0004_eduaddafiledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduaddacourse',
            name='CATEGORY',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='eduaddacourse',
            name='STATUS',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='eduaddanotes',
            name='CATEGORY',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='eduaddanotes',
            name='STATUS',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
