# Generated by Django 5.0 on 2025-01-15 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduaddaApp', '0005_eduaddacourse_category_eduaddacourse_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eduaddanotespurchase',
            old_name='PURCHASE_ID',
            new_name='NOTES_ID',
        ),
    ]
