# Generated by Django 5.0 on 2025-01-15 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduaddaApp', '0006_rename_purchase_id_eduaddanotespurchase_notes_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eduaddanotespurchase',
            old_name='NOTES_ID',
            new_name='PURCHASE_ID',
        ),
    ]
