# Generated by Django 5.0 on 2025-01-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduaddaApp', '0007_rename_notes_id_eduaddanotespurchase_purchase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduaddacoursepurchase',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eduaddacoursepurchase',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
