# Generated by Django 5.0 on 2025-01-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduaddaApp', '0008_eduaddacoursepurchase_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduaddanotespurchase',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eduaddanotespurchase',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
