# Generated by Django 5.0 on 2025-01-26 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduaddaApp', '0009_eduaddanotespurchase_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('SESSION_ID', models.AutoField(primary_key=True, serialize=False)),
                ('TOKEN', models.CharField(max_length=500)),
                ('DEVICE_INFO', models.CharField(blank=True, max_length=255, null=True)),
                ('IP_ADDRESS', models.GenericIPAddressField(blank=True, null=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('EXPIRES_AT', models.DateTimeField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduaddaApp.eduaddauser')),
            ],
        ),
    ]
