# Generated by Django 5.0 on 2025-01-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduaddaApp', '0010_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduaddauser',
            name='ABOUT_ME',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
