# Generated by Django 5.0 on 2025-01-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduaddaApp', '0011_eduaddauser_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduaddauser',
            name='PR_OTP',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eduaddauser',
            name='PR_OTP_TIME',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
