# Generated by Django 5.0 on 2025-03-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduaddaApp', '0012_eduaddauser_pr_otp_eduaddauser_pr_otp_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduaddaReview',
            fields=[
                ('REVIEW_ID', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.TextField(blank=True, default='', null=True)),
                ('REVIEW', models.TextField(blank=True, default='', null=True)),
                ('STAR', models.IntegerField(blank=True, default=0, null=True)),
                ('STATUS', models.IntegerField(blank=True, default=0, null=True)),
                ('PR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Eduadda_review',
            },
        ),
    ]
